### model
model_name_or_path: Qwen/Qwen2.5-32B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: train/zero3.json  
enable_liger_kernel: true
packing: true
neat_packing: true

messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

### dataset
dataset: open-thoughts/OpenThoughts2-1M 
template: qwen25
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_persistent_workers: true
dataloader_pin_memory: true
dataloader_num_workers: 4

### output
output_dir: saves/OpenThinker2-32B
logging_steps: 1
save_steps: 100
plot_loss: true

### train
global_batch_size: 512
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 8.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000